name: build-and-test
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: "PR"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n**Full Changelog**: https://github.com/tlinden/play/compare/#{{FROM_TAG}}...#{{TO_TAG}}\n#{{RELEASE_DIFF}}\n#{{CONTRIBUTORS}}\n",
              "pr_template": "- #{{TITLE}} (##{{NUMBER}}) by #{{AUTHOR}}\n#{{BODY}}",
              "empty_template": "- no changes",
              "categories": [
                {
                    "title": "## New Features",
                    "labels": ["add", "feature"]
                },
                {
                    "title": "## Bug Fixes",
                    "labels": ["fix", "bug", "revert"]
                },
                {
                    "title": "## Documentation Enhancements",
                    "labels": ["doc"]
                },
                {
                    "title": "## Refactoring Efforts",
                    "labels": ["refactor"]
                },
                {
                    "title": "## Miscelanneus Changes",
                    "labels": []
                }
              ],
              "ignore_labels": [
                 "duplicate", "good first issue", "help wanted", "invalid", "question", "wontfix"
              ],
              "label_extractor": [
                 {
                    "pattern": "(.) (.+)",
                    "target": "$1"
                 },
                 {
                    "pattern": "(.) (.+)",
                    "target": "$1",
                    "on_property": "title"
                 }
              ]
            }

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.github_release.outputs.changelog}}



# add comment
